- name: Installation of MongoDB in windows server
  hosts: all
  tasks:
    - name: Create directories for MongoDB
      win_file:
        path: C:\\Users\\data\\db
        state: directory
       
    - name: Download MSI file for MongoDB
      win_get_url:
        url: https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-4.4.7-signed.msi
        dest: C:\\Users\\mongodb.msi   
        
    - name: Install MongoDB Installer in Windows Server
      win_command: msiexec /i mongodb.msi /qb ADDLOCAL="ServerService,Client"
      args: 
        chdir: C:\\Users
        
    - name: Set env variable
      win_command: cmd.exe /c setx path "%PATH%;C:\Program Files\MongoDB\Server\4.4\bin" /M

